=== BirgitBoss/tractusX.sldt-semantic-models/io.catenax.shared.business_partner_certificate/1.0.0/gen/BusinesspartnerCertificate-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "description" : "A business partner certifcate describes a certification (eg ISO9001, IATF-16949) via a certifcate document  of a Catena-X business partner",
  "type" : "object",
  "components" : {
    "schemas" : {
      "urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait" : {
        "type" : "string",
        "description" : "The provided regular expression ensures that the BPNL is composed of prefix 'BPNL', 10 digits and two uppercase letters.",
        "pattern" : "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
      },
      "urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text" : {
        "type" : "string",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "urn_samm_io.catenax.business_partner_certificate_1.0.0_certificateTypeEntity" : {
        "description" : "Detailled entity of the certificate like IS09001:2015, IATF 16949:2015 or other, valid types are registered at BPN metadatacontroller",
        "type" : "object",
        "properties" : {
          "certificateType" : {
            "description" : "type of the certificate as defined on the document,valid types are registered at BPN metadatacontroller",
            "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
          },
          "certificateVersion" : {
            "description" : "Version of the certificate as defined on the document, usually the specific version of a certification standard",
            "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
          }
        },
        "required" : [ "certificateType" ]
      },
      "urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait" : {
        "type" : "string",
        "description" : "The provided regular expression ensures that the BPNS is composed of prefix 'BPNS', 10 digits and two uppercase letters.",
        "pattern" : "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
      },
      "urn_samm_io.catenax.business_partner_certificate_1.0.0_enclosedSiteEntity" : {
        "description" : "Optional enclosed sites where certificatation is valid including details about area of application",
        "type" : "object",
        "properties" : {
          "enclosedSiteBPN" : {
            "description" : "The BPN of an enclosed site ",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait"
          },
          "areaOfApplication" : {
            "description" : "Details on which areas / application types a certification is valid ",
            "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
          }
        },
        "required" : [ "enclosedSiteBPN" ]
      },
      "EnclosedSitesList" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/urn_samm_io.catenax.business_partner_certificate_1.0.0_enclosedSiteEntity"
        }
      },
      "urn_samm_io.catenax.business_partner_certificate_1.0.0_Date" : {
        "type" : "string",
        "format" : "date",
        "description" : "Describes a property which contains the date in english format."
      },
      "urn_samm_io.catenax.business_partner_certificate_1.0.0_trustLevelValue" : {
        "type" : "string",
        "description" : "The possible trust level values of certificate",
        "enum" : [ "none", "low", "high", "trusted" ]
      },
      "urn_samm_io.catenax.business_partner_certificate_1.0.0_trustValidatorCharacteristic" : {
        "description" : "The BPN of the data service provider who validate the given certificate",
        "type" : "object",
        "properties" : {
          "validatorName" : {
            "description" : "The optional name of the data service provider who validated the given certificate",
            "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
          },
          "validatorBPN" : {
            "description" : "The BPN of the data service provider who validated the given certificate",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait"
          }
        },
        "required" : [ "validatorBPN" ]
      }
    }
  },
  "properties" : {
    "businessPartnerNumber" : {
      "description" : "The BPN of the certified legal entity ",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait"
    },
    "type" : {
      "description" : "Type of the certificatation as defined on the document like IS09001, IATF 16949 or other",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.business_partner_certificate_1.0.0_certificateTypeEntity"
    },
    "registrationNumber" : {
      "description" : "Registration number of the certificate as in the certification document",
      "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
    },
    "areaOfApplication" : {
      "description" : "Details on which areas / application types a certification is valid ",
      "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
    },
    "enclosedSites" : {
      "description" : "Optional enclosed sites of the legal entity which are enclosed by the certification ",
      "$ref" : "#/components/schemas/EnclosedSitesList"
    },
    "validFrom" : {
      "description" : "certificate valid from as in the certification document.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.business_partner_certificate_1.0.0_Date"
    },
    "validUntil" : {
      "description" : "Certificate valid until as in the certification document. If certificate never expires value until expected to be 9999-12-31",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.business_partner_certificate_1.0.0_Date"
    },
    "issuer" : {
      "description" : "The BPN of the issuing Authority e.g. TUEV Sued ",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait"
    },
    "trustLevel" : {
      "description" : "The trust level of the given certificate none,low, high, trusted",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.business_partner_certificate_1.0.0_trustLevelValue"
    },
    "validator" : {
      "description" : "The BPN of the data service provider who validate the given certificate",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.business_partner_certificate_1.0.0_trustValidatorCharacteristic"
    },
    "uploader" : {
      "description" : "The BPN of the business partner who originally provided the certifcate data or document e.g. Mercedes Benz AG",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait"
    },
    "documentID" : {
      "description" : "The id of the certificate document as stored by the data service provider for physical download via API",
      "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
    }
  },
  "required" : [ "businessPartnerNumber", "type", "registrationNumber", "validFrom", "validUntil", "trustLevel", "documentID" ]
}

=== BirgitBoss/tractusX.sldt-semantic-models/io.catenax.shared.business_partner_certificate/1.0.0/gen/BusinessPartnerCertificate.json
{
  "businessPartnerNumber" : "BPNL00000003AYRE",
  "enclosedSites" : [ {
    "areaOfApplication" : "Development, Marketing und Sales and also Procurement for interiour components",
    "enclosedSiteBPN" : "BPNS00000003AYRE"
  } ],
  "registrationNumber" : "12 198 54182 TMS",
  "uploader" : "BPNL00000003AYRE",
  "validator" : {
    "validatorName" : "Data Service Provider X",
    "validatorBPN" : "BPNL00000007YREZ"
  },
  "validUntil" : "2026-01-24",
  "documentID" : "DOC-UID-123456789",
  "validFrom" : "2023-01-25",
  "trustLevel" : "none",
  "type" : {
    "certificateVersion" : "2015",
    "certificateType" : "ISO9001"
  },
  "areaOfApplication" : "Development, Marketing und Sales and also Procurement for interiour components",
  "issuer" : "BPNL00000023ZAVC"
}
