=== BirgitBoss/tractusX.sldt-semantic-models/io.catenax.quality_task/2.0.0/gen/QualityTask-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "description" : "A quality task (qTask) defines why data is exchanged between 2 or more companies and what insights should be generated out of the transferred data. In addition there is a flag, what happens with the transferred data when this qTask is closed",
  "type" : "object",
  "components" : {
    "schemas" : {
      "urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait" : {
        "type" : "string",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
        "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
      },
      "urn_samm_io.catenax.quality_task_2.0.0_StatusCharacteristic" : {
        "type" : "string",
        "description" : "Enumeration of the different status values",
        "enum" : [ "new", "in progress", "completed", "closed" ]
      },
      "urn_samm_io.catenax.quality_task_2.0.0_Date" : {
        "type" : "string",
        "format" : "date",
        "description" : "Describes a Property which contains the date and time with an optional timezone."
      },
      "urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text" : {
        "type" : "string",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "urn_samm_io.catenax.quality_task_2.0.0_DataDeletionEnumeration" : {
        "type" : "string",
        "description" : "Enumeration of possible data deletions entries.",
        "enum" : [ "delete-data-after-closing", "no-deletion-after-closing" ]
      },
      "urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait" : {
        "type" : "string",
        "description" : "The provided regular expression ensures that the BPNL is composed of prefix 'BPNL', 10 digits and two uppercase letters.",
        "pattern" : "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
      },
      "urn_samm_io.catenax.shared.contact_information_3.0.0_EMailTrait" : {
        "type" : "string",
        "description" : "Regular expression for mail address as defined in W3C.",
        "pattern" : "^[a-zA-Z0-9.!#$%&?*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$"
      },
      "urn_samm_io.catenax.quality_task_2.0.0_Company" : {
        "description" : "One company involved in this qTask",
        "type" : "object",
        "properties" : {
          "cxBusinessPartnerNumber" : {
            "description" : "The Catena-X business partner number for this company.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait"
          },
          "name" : {
            "description" : "Name of the comapny",
            "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
          },
          "email" : {
            "description" : "An email address.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.contact_information_3.0.0_EMailTrait"
          }
        },
        "required" : [ "cxBusinessPartnerNumber" ]
      },
      "urn_samm_io.catenax.quality_task_2.0.0_ListOfCompanies" : {
        "description" : "A list of all companies involved in this qTask",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_Company"
        }
      }
    }
  },
  "properties" : {
    "qualityTaskId" : {
      "description" : "A unique quality task identifier within the Catena-X dataspace. The unique id uses the Catena-X UUID trait.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait"
    },
    "status" : {
      "description" : "Status of this quality task",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_StatusCharacteristic"
    },
    "creationDate" : {
      "description" : "Timestamp when this qTask was created",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_Date"
    },
    "title" : {
      "description" : "Working title for this qTask",
      "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
    },
    "description" : {
      "description" : "Description what should be done in this qTask",
      "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
    },
    "component" : {
      "description" : "The component that should be investigated in this qTask.",
      "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
    },
    "dataDeletion" : {
      "description" : "What should be done with the data after this qTask is closed",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_DataDeletionEnumeration"
    },
    "listOfCompanies" : {
      "description" : "A list of companies involved in this quality task",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_ListOfCompanies"
    }
  },
  "required" : [ "qualityTaskId" ]
}

=== BirgitBoss/tractusX.sldt-semantic-models/io.catenax.quality_task/2.0.0/gen/QualityTask.json
{
  "component" : "ComponentA",
  "listOfCompanies" : [ {
    "name" : "Company A",
    "email" : "test.mail@example.com",
    "cxBusinessPartnerNumber" : "BPNL000000000123"
  } ],
  "qualityTaskId" : "Qtask_2xckuQ",
  "description" : "Please evaluate why there is a high number of customer complaints with ComponentA if the vehicle is between 10000-30000km.",
  "creationDate" : "2022-11-11",
  "title" : "Evaluation of ComponentA in CarmodelB in country DE",
  "status" : "new",
  "dataDeletion" : "delete-data-after-closing"
}
